### PR TITLE
Helper functions to create `FormData` and URI encoded data (`FormDataURLEncoded`).

### PR DESCRIPTION
**Pull request by jprider63**
These are functions to help create AJAX requests. Some of this might be better to put into `DOM.XHR.Types`.

### CODE REVIEW

**Comment by zudov** [comment]
Hi, I've only noticed this issue today, and yesterday I published this: https://pursuit.purescript.org/packages/purescript-form-urlencoded

That only solves the problem with `FormDataURLEncoded` though.
I think it's nicer to have these things in a separate libraries, but it would be nice to the dependency so that `affjax` would define an instance of `Requestable FormURLEncoded`

**Comment by jprider63** [comment]
I'm not sure the best way that this should be packaged. My only preference is that importing purescript-affjax should include this functionality so that users don't need to search for additional packages/modules. Any thoughts @garyb? I think it'd be useful to resolve this soon so that others can make use of it.

**Comment by zudov** [comment]
I think that both of these things have to be in the separate libraries, since they can be useful without `purescript-affjax`.

I've gotten `purescript-form-urlencoded` in a good shape, and would like to push it into `purescript-contrib`. So there is nothing that stops us from moving [this instance](https://github.com/zudov/purescript-form-urlencoded/blob/4690b06768bd02a9845ebf6339aa8eb5adc6f37e/src/Data/FormURLEncoded.purs#L44) into `Network.HTTP.Affjax.Request`. This would get half of the problem solved.

**Comment by garyb** [comment]
@zudov I've invited you to contrib, I'm all for moving `form-urlencoded` there and swapping the dependency.

@jprider63 sorry I left this one hanging after saying on IRC I'd get it sorted out if you submitted a PR. I think @zudov might be right that perhaps the `FormData` functions should go in `purescript-dom` though, as we [do have the type defined there](https://github.com/purescript-contrib/purescript-dom/blob/06aea09664d5c98212f50e4f03f75b123705a358/src/DOM/XHR/Types.purs#L6).

If you could open a PR there for a new `DOM.XHR.FormData` module with your functions in it I'd much appreciate it.

**Comment by jprider63** [comment]
I just created pull request purescript-contrib/purescript-dom#39. I think the only thing left to do is merge in @zudov's branch for the `Requestable FormUrlEncoded` instance.

**Comment by garyb** [comment]
Noth have been merged and released now, is this okay to close then?

**Comment by jprider63** [comment]
Yup!

**Pull request closed without merging**
