### PR TITLE
Update dependency, fix warning

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by jonsterling** [comment]
I see stuff like `Error: Expected a Right value` in the build log. Is this expected?

**Comment by garyb** [comment]
I don't think so - I noticed that too, looking into it now. A bit alarming!

**Comment by garyb** [comment]
Looks like this has been happening for a while too: https://travis-ci.org/slamdata/purescript-affjax/builds/78057670 (that's the current `master`)

**Comment by garyb** [comment]
Alright, it seems to be a travis issue:

```
The command "node ./test-server.js &" exited with 0.
```

So the test server is stopping before the tests run. I'll merge this for now so I can get this Halogen PR finished up, but I'll open an issue about the tests.

**Comment by jonsterling** [comment]
Interesting, good to know!

**Pull request merged**
