### PR TITLE
node.js support, via npm package 'xmlhttprequest'

### LINKED ISSUE #29: Support node.js
As requested by @hdgarrood, who also mentioned he'd look at working on it.

The would entail detecting whether we're running in node currently and then if so, using the `http` module to make the requests, and copying any XHR behaviours we rely on to produce a response currently.

### PR DESCRIPTION
**Pull request by hdgarrood**
Fixes #29. This passes all the tests in my other PR, but currently you have to set up an http server on port 80 to proxy to the test server to get them to work.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Also if you merge #31 first, then I can rebase this and set Travis up to run the tests on node.js. :)

**Comment by garyb** [comment]
Please do!

**Comment by garyb** [comment]
Actually I'll sort out #30 first.

**Comment by hdgarrood** [comment]
I couldn't get it to run in Gulp, so I tried it inside the travis script, but that doesn't appear to work either (if you look at the travis log, it looks like it's only running the first test). Issuing the same commands as those that are in the travis script does work locally though. I've no idea what's wrong or how to fix it :(

**Comment by garyb** [comment]
Can you rebase this please? I've broken one of your PRs once again somehow :wink:

**Comment by garyb** [comment]
Thanks!

**Comment by garyb** [comment]
It's great that the tests can be run by Travis now too, thanks very much. :fireworks:

**Pull request merged**
