### PR TITLE
Updates for 0.7

### PR DESCRIPTION
**Pull request by qxjit**
Made these updates while upgrade our code to 0.7.

I tried to imitate the gulpfile in purescript-aff in updating this one. If there's something you'd like set up differently, just let me know.

### CODE REVIEW

**Comment by jdegoes** [comment]
Thanks for the PR, @qxjit! Note the build is not currently passing.

Review / merge by @garyb.

**Comment by qxjit** [comment]
Oops, my bad. Looks like I missed the names of the binaries in the travis.yml.

**Comment by qxjit** [comment]
:/ It looks like the travis build is still looking for the old binary names, but the build includes the commit that changes those names. Did I miss an update somewhere else?

**Comment by jdegoes** [comment]
It's failing for the following reason:

> The command "sudo tar zxvf $HOME/purescript.tar.gz -C /usr/local/bin purescript/psc{,i,-docs,-make} --strip-components=1" failed and exited with 2 during .

**Comment by qxjit** [comment]
Oh, I totally missed that the binaries were named in there twice. I will try again. Sorry! :)

**Comment by garyb** [comment]
Thanks!

**Comment by garyb** [comment]
@qxjit I made a few tweaks to the build process that you might like to incorporate if you do any more of these in the future:

- There are gulp tasks for `jshint` and `jscs` rather than `jsvalidate` now (configured by the `.jscsrc` and `.jshintrc` files)
- The Travis build uses a slightly different setup so we can have faster `sudo: false` container builds.

**Comment by qxjit** [comment]
@garyb Excellent, thanks!

**Comment by garyb** [comment]
Oh also, I switched the bower dependencies to use `^` rather than `~`, as `^` imposes a lower bound that seems to work better when you do have a variety of dependencies on different minor versions in a project.

**Pull request merged**
