### PR TITLE
Add `Requestable FormURLEncoded` instance

### PR DESCRIPTION
**Pull request by zudov**
See discussion in https://github.com/slamdata/purescript-affjax/pull/57

### CODE REVIEW

**Comment by garyb** [comment]
Got some build errors here due to there being 0.8-style imports in `form-urlencoded` - this library isn't really 0.8-ready yet, I was going to wait until we've release 0.8.1 and then the new prelude/core libraries before updating everything else.

**Comment by zudov** [comment]
Yes, makes sense. I'll make the changes pre 0.8 friendly

**Comment by zudov** [comment]
jf

**Comment by zudov** [comment]
It's now fixed

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
