### PR TITLE
updates for 0.9.1

### PR DESCRIPTION
**Pull request by Thimoteus**
I did this pretty mechanically, following warnings and errors and fixing them appropriately.

### CODE REVIEW

**Comment by jdegoes** [comment]
@Thimoteus Thanks you! The build is not passing, however. Can you look into that?

**Comment by garyb** [comment]
Looks like the `package.json` needs a few updates for a new pulp and purescript.

While you're in there, could you:
- Add a `purescript-psa` dependency, and build with `pulp build --censor-lib --strict` please? Something like we have [in strongcheck](https://github.com/purescript-contrib/purescript-strongcheck/blob/c4eb4b2b1a98daa366f85dcfa9673b03fcd4c9d2/package.json). 
- Update Travis to build first then test, also [like we have in strongcheck](https://github.com/purescript-contrib/purescript-strongcheck/blob/c4eb4b2b1a98daa366f85dcfa9673b03fcd4c9d2/.travis.yml). (This ensures we're not accidentally relying on a `devDependency` in the library).

Thanks!

**Comment by Thimoteus** [comment]
Wow, that package.json had some old stuff. I'll try to get this working on travis then squash once it works.

**Comment by jdegoes** [comment]
@Thimoteus Thanks! 

@garyb This looks good to me, any comments?

**Comment by garyb** [comment]
Looks great, thanks!

**Pull request merged**
